"""users_hash

Revision ID: 4400824d7bd3
Revises: 0c3329d6a5e9
Create Date: 2025-05-01 20:51:48.908538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4400824d7bd3'
down_revision: Union[str, None] = '0c3329d6a5e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('api_key_hash', sa.String(), nullable=False))
    op.drop_constraint('users_encrypted_api_key_key', 'users', type_='unique')
    op.create_unique_constraint(None, 'users', ['api_key_hash'])
    op.drop_column('users', 'encrypted_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('encrypted_api_key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    op.create_unique_constraint('users_encrypted_api_key_key', 'users', ['encrypted_api_key'])
    op.drop_column('users', 'api_key_hash')
    # ### end Alembic commands ###
