"""update

Revision ID: f0622fcceeed
Revises: 4400824d7bd3
Create Date: 2025-05-18 14:10:10.921468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0622fcceeed'
down_revision: Union[str, None] = '4400824d7bd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('encrypted_api_key', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'users', ['encrypted_api_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'encrypted_api_key')
    op.drop_column('instruments', 'is_active')
    # ### end Alembic commands ###
