"""balance_update

Revision ID: fbcc891d65a6
Revises: c194ae0fe90f
Create Date: 2025-05-18 16:39:50.316948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbcc891d65a6'
down_revision: Union[str, None] = 'c194ae0fe90f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balances', sa.Column('instrument_id', sa.Uuid(), nullable=False))
    op.drop_constraint('uix_user_ticker', 'balances', type_='unique')
    op.create_unique_constraint('uix_user_instrument', 'balances', ['user_id', 'instrument_id'])
    op.create_foreign_key(None, 'balances', 'instruments', ['instrument_id'], ['id'], ondelete='CASCADE')
    op.drop_column('balances', 'ticker')
    op.drop_column('instruments', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('balances', sa.Column('ticker', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'balances', type_='foreignkey')
    op.drop_constraint('uix_user_instrument', 'balances', type_='unique')
    op.create_unique_constraint('uix_user_ticker', 'balances', ['user_id', 'ticker'])
    op.drop_column('balances', 'instrument_id')
    # ### end Alembic commands ###
